"use client";
import {useState} from "react";
import {CheckCircle2,ImagePlus} from "lucide-react";
import type {partners} from "../../db/schema";

type Profile=typeof partners.$inferSelect|undefined;
export function ProfileForm({email,profile}:{email:string,profile:Profile}){
  const[saved,setSaved]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false),[imageVersion,setImageVersion]=useState(Date.now());
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError("");setSaved(false);setBusy(true);const data=new FormData(e.currentTarget),file=data.get("image");data.delete("image");try{const r=await fetch('/api/partner-profile',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(data.entries()))});const d=await r.json();if(!r.ok)throw new Error(d.error||'Profilen kunde inte sparas.');if(file instanceof File&&file.size){const upload=new FormData();upload.set('image',file);const ur=await fetch('/api/partner-image',{method:'POST',body:upload});const ud=await ur.json();if(!ur.ok)throw new Error(ud.error||'Bilden kunde inte laddas upp.');setImageVersion(Date.now())}setSaved(true)}catch(err){setError(err instanceof Error?err.message:'Profilen kunde inte sparas.')}finally{setBusy(false)}}
  const complete=profile?.imageKey?"75":"50";
  return <form className="profile-form" onSubmit={submit}><div className="profile-progress"><div><b>Din profil är {complete}% komplett</b><p>Grunduppgifterna och bilden används på era deals.</p></div><span>{complete}%</span></div>{saved&&<div className="profile-saved"><CheckCircle2/>Profil och bild är sparade.</div>}{error&&<div className="data-error">{error}</div>}<section><h2>Omslagsbild</h2><div className="venue-image-field">{profile?.imageKey?<img key={imageVersion} src={`/api/partner-image?v=${imageVersion}`} alt="Anläggningens omslagsbild"/>:<div className="image-placeholder"><ImagePlus/><span>Ingen bild uppladdad</span></div>}<label>Välj en JPG-, PNG- eller WebP-bild<input name="image" type="file" accept="image/jpeg,image/png,image/webp"/><small>Max 8 MB. Bilden beskärs automatiskt i visningen.</small></label></div></section><section><h2>Grunduppgifter</h2><div className="form-grid"><label>Anläggningens namn<input required name="name" defaultValue={profile?.name||""}/></label><label>Kontaktmail<input value={email} disabled/></label><label>Telefon<input name="phone" defaultValue={profile?.phone||""} placeholder="+46…"/></label><label>Webbplats<input name="website" defaultValue={profile?.website||""} placeholder="https://"/></label></div><label>Beskrivning<textarea name="description" defaultValue={profile?.description||""} placeholder="Beskriv anläggningen, miljön och vad som gör era möten speciella."/></label></section><section><h2>Kapacitet</h2><div className="form-grid"><label>Antal hotellrum<input name="rooms" type="number" min="0" defaultValue={profile?.rooms||0}/></label><label>Max möteskapacitet<input name="capacity" type="number" min="0" defaultValue={profile?.capacity||0}/></label></div></section><button className="save-deal" disabled={busy}>{busy?'Sparar…':'Spara profil och bild'}</button></form>
}
