import {env} from "cloudflare:workers";
import {headers} from "next/headers";
import {eq} from "drizzle-orm";
import {getDb} from "../../../db";
import {partners} from "../../../db/schema";

const allowed=new Set(["image/jpeg","image/png","image/webp"]);
export async function GET(){const h=await headers(),email=h.get("oai-authenticated-user-email");if(!email)return new Response("Logga in.",{status:401});const[profile]=await getDb().select().from(partners).where(eq(partners.ownerEmail,email)).limit(1);if(!profile?.imageKey)return new Response("Bild saknas.",{status:404});const object=await env.BUCKET.get(profile.imageKey);if(!object)return new Response("Bild saknas.",{status:404});const response=new Response(object.body);response.headers.set("content-type",object.httpMetadata?.contentType||"image/jpeg");response.headers.set("cache-control","private, max-age=60");return response}
export async function POST(req:Request){try{const h=await headers(),email=h.get("oai-authenticated-user-email");if(!email)return Response.json({error:"Logga in för att ladda upp en bild."},{status:401});const form=await req.formData(),file=form.get("image");if(!(file instanceof File)||!file.size)return Response.json({error:"Välj en bild."},{status:400});if(!allowed.has(file.type))return Response.json({error:"Bilden måste vara JPG, PNG eller WebP."},{status:400});if(file.size>8*1024*1024)return Response.json({error:"Bilden får vara högst 8 MB."},{status:400});const db=getDb(),[profile]=await db.select().from(partners).where(eq(partners.ownerEmail,email)).limit(1);if(!profile)return Response.json({error:"Spara anläggningsprofilen först."},{status:400});const ext=file.type==="image/png"?"png":file.type==="image/webp"?"webp":"jpg",key=`venues/${profile.id}/${crypto.randomUUID()}.${ext}`;await env.BUCKET.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type}});const oldKey=profile.imageKey;await db.update(partners).set({imageKey:key}).where(eq(partners.ownerEmail,email));if(oldKey)await env.BUCKET.delete(oldKey);return Response.json({ok:true})}catch{return Response.json({error:"Bilden kunde inte laddas upp just nu."},{status:500})}}
