import {headers} from "next/headers";
import {and,eq} from "drizzle-orm";
import {getDb} from "../../../../../db";
import {deals,leadMessages,leads,notificationOutbox} from "../../../../../db/schema";
export async function POST(req:Request,{params}:{params:Promise<{leadId:string}>}){
 try{const h=await headers(),email=h.get("oai-authenticated-user-email");if(!email)return Response.json({error:"Logga in för att svara."},{status:401});const{leadId}=await params,p=await req.json(),body=p.body?.trim();if(!body)return Response.json({error:"Skriv ett meddelande."},{status:400});if(body.length>5000)return Response.json({error:"Meddelandet är för långt."},{status:400});const db=getDb(),[lead]=await db.select().from(leads).where(eq(leads.leadId,leadId)).limit(1);if(!lead)return Response.json({error:"Förfrågan hittades inte."},{status:404});let role:"member"|"partner",recipient:string;
 if(lead.email.toLowerCase()===email.toLowerCase()){role="member";if(!lead.dealId)return Response.json({error:"Den allmänna förfrågan hanteras av MeetingDeal."},{status:400});const[deal]=await db.select().from(deals).where(eq(deals.dealId,lead.dealId)).limit(1);recipient=deal?.ownerEmail||"fredrik@helf.se"}
 else{const[deal]=lead.dealId?await db.select().from(deals).where(and(eq(deals.dealId,lead.dealId),eq(deals.ownerEmail,email))).limit(1):[];if(!deal)return Response.json({error:"Du har inte åtkomst till förfrågan."},{status:403});role="partner";recipient=lead.email}
 const[message]=await db.insert(leadMessages).values({leadId,senderRole:role,senderEmail:email,body}).returning();await db.insert(notificationOutbox).values({eventType:role==="partner"?"partner_reply":"member_reply",leadId,recipientEmail:recipient,subject:`Nytt svar på MeetingDeal-förfrågan ${leadId}`,body:`Du har fått ett nytt svar i dialogen för ${lead.destination}. Logga in för att läsa och svara.`});return Response.json({message},{status:201})}catch{return Response.json({error:"Meddelandet kunde inte skickas."},{status:500})}}
