import Link from "next/link";import {desc,eq} from "drizzle-orm";import {ArrowRight,ShieldCheck,Sparkles} from "lucide-react";import {getDb} from "../db";import {deals} from "../db/schema";import {LeadForm} from "./components/LeadForm";import {PublicDealCard} from "./components/PublicDealCard";
export const dynamic="force-dynamic";
export default async function Home(){let rows:typeof deals.$inferSelect[]=[];try{rows=await getDb().select().from(deals).where(eq(deals.status,"active")).orderBy(desc(deals.createdAt)).limit(6)}catch{}return <main><header className="public-header"><Link className="brand" href="/"><span>MEETING</span><b>DEAL</b></Link><nav><a href="#deals">Deals</a><a href="#request">Allmän förfrågan</a></nav><div className="portal-choices"><a className="member-choice" href="/member" target="_top">Member Portal <ArrowRight size={16}/></a><a className="partner-choice" href="/partner" target="_top">Partnerportal <ArrowRight size={16}/></a></div></header>
<section className="hero-v2"><div className="hero-copy"><p className="kicker">Konferensdeals i Skandinavien</p><h1>Rätt möte.<br/>Rätt plats.<br/><em>Rätt pris.</em></h1><p className="hero-lead">Sök bland publicerade konferens- och mötesdeals – eller låt oss jämföra alternativen åt er.</p><form className="hero-search" action="#deals"><label>Destination<input placeholder="Stad eller region"/></label><label>Antal personer<input type="number" min="8" defaultValue="40"/></label><label>Mötestyp<select defaultValue="Helpension"><option>Helpension</option><option>Dagkonferens</option><option>Kickoff</option><option>Ledningsmöte</option></select></label><button>Visa deals <ArrowRight size={18}/></button></form></div><div className="hero-visual"><div className="hero-image"/><div className="floating-deal"><span>NYA DEALS</span><strong>{rows.length}</strong><small>publicerade just nu</small></div></div></section>
<section className="value-row"><div><span>01</span><b>En förfrågan</b><small>Slipp kontakta flera anläggningar.</small></div><div><span>02</span><b>Noga utvalt</b><small>Vi väger pris, kvalitet och villkor.</small></div><div><span>03</span><b>Hela prisbilden</b><small>Se totalpris och faktisk besparing.</small></div></section>
<section className="deals" id="deals"><div className="section-title"><div><p className="kicker green">Publicerade just nu</p><h2>Deals värda att<br/>samlas kring.</h2></div><p>Här visas erbjudanden som anläggningarna själva har publicerat.</p></div>{rows.length?<div className="deal-grid">{rows.map(d=><PublicDealCard key={d.id} deal={d}/>)}</div>:<div className="public-empty"><h3>Inga deals är publicerade just nu</h3><p>Nya erbjudanden kommer snart. Ni kan fortfarande skicka en generell förfrågan nedan.</p></div>}</section>
<section className="member-invite"><div><p className="kicker">För företag och mötesbokare</p><h2>Samla era mötesbehov på ett ställe.</h2><p>I Member Portal skapar ni en företagsprofil, ser aktuella deals och skickar förfrågningar med era uppgifter förifyllda.</p></div><a href="/member" target="_top">Öppna Member Portal <ArrowRight size={18}/></a></section>
<section className="request-section" id="request"><div className="request-intro"><p className="kicker">Vi gör jobbet åt er</p><h2>En förfrågan.<br/>Flera relevanta alternativ.</h2><p>Berätta vad ni behöver. Varje förfrågan får ett unikt lead-ID och skyddas i MeetingDeal-systemet.</p><div className="protect"><ShieldCheck/><span><b>Lead protection</b><small>Er förfrågan hanteras och följs upp genom MeetingDeal.</small></span></div></div><LeadForm/></section>
<section className="partner-teaser"><div><p className="kicker">För hotell & mötesanläggningar</p><h2>Fyll lediga datum.<br/>Inte prislistan.</h2></div><div><p>Skapa exklusiva deals, styr när de syns och följ varje introducerat lead.</p><Link href="/partner">Öppna partnerportalen <ArrowRight size={18}/></Link></div></section><footer><Link className="brand" href="/"><span>MEETING</span><b>DEAL</b></Link><p>Rätt möte. Rätt plats. Rätt pris.</p><span><Sparkles size={16}/> Smart konferensbokning.</span></footer></main>}
