import Link from "next/link";
import {ArrowRight,Check,ShieldCheck,Sparkles} from "lucide-react";
import {LeadForm} from "./components/LeadForm";
const deals=[
{id:"MD-45827",badge:"HOT MEETINGDEAL",name:"Nackarpsdalen Gästgiveri",place:"Söderåsen, Skåne",score:"9,3",price:"2 195",old:"2 995",save:"32 000",image:"https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1100&q=85",includes:["Helpension","Spa","Konferenslokal"]},
{id:"MD-61804",badge:"LAST MINUTE",name:"Skärgårdshotellet",place:"Vaxholm, Stockholm",score:"9,0",price:"1 845",old:"2 395",save:"22 000",image:"https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1100&q=85",includes:["Havsutsikt","Bastu","Båttransfer"]},
{id:"MD-77291",badge:"MEETINGDEAL SELECT",name:"The Foundry Copenhagen",place:"Köpenhamn, Danmark",score:"9,6",price:"2 495",old:"2 895",save:"16 000",image:"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1100&q=85",includes:["LED-vägg","Private dining","Cityläge"]}];
export default function Home(){return <main><header className="public-header"><Link className="brand" href="/"><span>MEETING</span><b>DEAL</b></Link><nav><a href="#deals">Deals</a><a href="#request">Personlig hjälp</a><Link href="/partner">För partners</Link></nav><Link className="nav-cta" href="/partner">Partnerportal <ArrowRight size={16}/></Link></header>
<section className="hero-v2"><div className="hero-copy"><p className="kicker">Konferensdeals i Skandinavien</p><h1>Rätt möte.<br/>Rätt plats.<br/><em>Rätt pris.</em></h1><p className="hero-lead">Sök bland handplockade konferens- och mötesdeals – eller låt oss jämföra alternativen åt er.</p><form className="hero-search" action="#deals"><label>Destination<input placeholder="Stad eller region"/></label><label>Antal personer<input type="number" min="8" defaultValue="40"/></label><label>Mötestyp<select defaultValue="Helpension"><option>Helpension</option><option>Dagkonferens</option><option>Kickoff</option><option>Ledningsmöte</option></select></label><button>Visa deals <ArrowRight size={18}/></button></form></div><div className="hero-visual"><div className="hero-image"/><div className="floating-deal"><span>VECKANS DEAL</span><strong>1 895 kr</strong><small>/ person · Ystad</small></div></div></section>
<section className="value-row"><div><span>01</span><b>En förfrågan</b><small>Slipp kontakta flera anläggningar.</small></div><div><span>02</span><b>Noga utvalt</b><small>Vi väger pris, kvalitet och villkor.</small></div><div><span>03</span><b>Hela prisbilden</b><small>Se totalpris och faktisk besparing.</small></div></section>
<section className="deals" id="deals"><div className="section-title"><div><p className="kicker green">Utvalda just nu</p><h2>Deals värda att<br/>samlas kring.</h2></div><p>MeetingDeal handlar om rätt kombination av anläggning, innehåll, villkor och pris.</p></div><div className="deal-grid">{deals.map(d=><article className="deal-card" key={d.id}><div className="deal-photo" style={{backgroundImage:`linear-gradient(0deg,rgba(5,28,26,.65),transparent 55%),url('${d.image}')`}}><span>{d.badge}</span><b>{d.score} / 10</b></div><div className="deal-content"><small>{d.place} · {d.id}</small><h3>{d.name}</h3><div className="chips">{d.includes.map(x=><i key={x}><Check size={13}/>{x}</i>)}</div><div className="price"><div><small>MeetingDeal från</small><strong>{d.price} kr</strong><del>Ord. {d.old} kr</del></div><div><b>Spara {d.save} kr</b><small>vid 40 personer</small></div></div><a href="#request">Säkra dealen <ArrowRight size={17}/></a></div></article>)}</div></section>
<section className="request-section" id="request"><div className="request-intro"><p className="kicker">Vi gör jobbet åt er</p><h2>En förfrågan.<br/>Flera relevanta alternativ.</h2><p>Berätta vad ni behöver. Varje förfrågan får ett unikt lead-ID och skyddas i MeetingDeal-systemet.</p><div className="protect"><ShieldCheck/><span><b>Lead protection</b><small>Er förfrågan hanteras och följs upp genom MeetingDeal.</small></span></div></div><LeadForm/></section>
<section className="partner-teaser"><div><p className="kicker">För hotell & mötesanläggningar</p><h2>Fyll lediga datum.<br/>Inte prislistan.</h2></div><div><p>Skapa exklusiva deals, styr när de syns och följ varje introducerat lead.</p><Link href="/partner">Öppna partnerportalen <ArrowRight size={18}/></Link></div></section>
<footer><Link className="brand" href="/"><span>MEETING</span><b>DEAL</b></Link><p>Rätt möte. Rätt plats. Rätt pris.</p><span><Sparkles size={16}/> Smart konferensbokning.</span></footer></main>}
